name: Download the firmware

inputs:
  FIRMWARE_VARIANT:
    required: true
    type: string
  FIRMWARE_RUN_ID:
    required: false
    type: string

runs:
  using: "composite"
  steps:
# when the build is NOT part of a continuous release, the firware hex from the most recent continuous release will be packaged with the desktop interface
    - name: Determine download url for the firmware from the most recent continuous release
      if: github.event.workflow != '.github/workflows/continuous.yml' 
      id: run_query
      run: |
        HEX_URL=$(gh api graphql -f query='query {repository ( owner : "brentfpage", name: "Labrador") {release ( tagName: "continuous" ) {releaseAssets(first:10) {nodes {downloadUrl}}}}}' | jq -r '.data.repository.release.releaseAssets.nodes[] | select(.downloadUrl| test("${{ inputs.FIRMWARE_VARIANT }}.hex")) | .[]')
        echo "firmware_url=${HEX_URL}" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash

# query description: get at most 10 assets from the most recent continuous release (assume there are fewer than 10), find the one that includes FIRMWARE_VARIANT.hex in the download url
# prettified (ish) query:
# query {\
#         repository ( owner : "espotek-org", name: "Labrador") {\
#           release ( tagName: "continuous" ) {\
#             releaseAssets(first:10) {\
#               nodes {\
#                 downloadUrl\
#               }\
#             }\
#           }\
#         }\
#       }\
# ' | jq -r '.data.repository.release.releaseAssets.nodes[] | select(.downloadUrl| test("${{ inputs.FIRMWARE_VARIANT }}.hex")) | .[]'

    - name: Download firmware from most recent continuous release
      if: github.event.workflow != '.github/workflows/continuous.yml' 
      run: |
        mkdir asset-hex
        wget --directory-prefix=asset-hex ${{ steps.run_query.outputs.firmware_url }}
      shell: bash

# when the build is part of a continuous release, the release's firmware hex will be packaged with the desktop interface
    - name: Download firmware from in-process continuous release
      if: github.event.workflow == '.github/workflows/continuous.yml' 
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ inputs.FIRMWARE_RUN_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: move firmware to appropriate directory
      run: |
        mv asset-hex/*${{ inputs.FIRMWARE_VARIANT }}.hex Desktop_Interface/resources/firmware
      shell: bash





