name: Build macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-dmg:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew dependencies
        run: |
          brew update
          brew remove --force $(brew list --formula) || true
          brew install fftw libomp qt@5 libusb eigen
          brew link libomp qt@5 --force

      - name: Build librador
        working-directory: Librador_API/___librador/librador
        run: |
          qmake -config release
          make -j$(sysctl -n hw.ncpu)

      - name: Build librademo
        working-directory: Librador_API/___librador/librademo
        run: |
          qmake -config release
          make -j$(sysctl -n hw.ncpu)

      - name: Build basicdemo
        working-directory: Librador_API/___librador/basicdemo
        run: |
          qmake -config release
          make -j$(sysctl -n hw.ncpu)

      - name: Build macOS app
        working-directory: Desktop_Interface
        run: |
          qmake -config release
          make -j$(sysctl -n hw.ncpu)
          macdeployqt Labrador.app -verbose=2 -dmg -libpath=build_mac/libdfuprog/lib/
          mv Labrador.dmg Labrador-$(git rev-parse --short HEAD).dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asset-dmg
          path: Desktop_Interface/Labrador*.dmg
          compression-level: 0
          if-no-files-found: error
